import { IInstrucoes } from "../App";

export const Instrucao1: IInstrucoes[] = [
  {
    id: "1",
    nome: "Ldr",
    entrada1: "F6",
    entrada2: "34",
    entrada3: "R2",
    enviada: false,
    executada: false,
    escrita: false,
    commited: false,
    descartada: false,
  },
  {
    id: "2",
    nome: "Ldr",
    entrada1: "F2",
    entrada2: "45",
    entrada3: "R3",
    enviada: false,
    executada: false,
    escrita: false,
    commited: false,
    descartada: false,
  },
  {
    id: "3",
    nome: "Mul",
    entrada1: "F0",
    entrada2: "F2",
    entrada3: "F4",
    enviada: false,
    executada: false,
    escrita: false,
    commited: false,
    descartada: false,
  },
  {
    id: "4",
    nome: "Sub",
    entrada1: "F8",
    entrada2: "F6",
    entrada3: "F2",
    enviada: false,
    executada: false,
    escrita: false,
    commited: false,
    descartada: false,
  },
  {
    id: "5",
    nome: "Div",
    entrada1: "F10",
    entrada2: "F0",
    entrada3: "F6",
    enviada: false,
    executada: false,
    escrita: false,
    commited: false,
    descartada: false,
  },
  {
    id: "6",
    nome: "Add",
    entrada1: "F6",
    entrada2: "F8",
    entrada3: "F2",
    enviada: false,
    executada: false,
    escrita: false,
    commited: false,
    descartada: false,
  },
];

export const Instrucao2: IInstrucoes[] = [
  {
    id: "1",
    nome: "Ldr",
    entrada1: "F6",
    entrada2: "34",
    entrada3: "R2",
    enviada: false,
    executada: false,
    escrita: false,
    commited: false,
    descartada: false,
  },
  {
    id: "2",
    nome: "Ldr",
    entrada1: "F2",
    entrada2: "45",
    entrada3: "R3",
    enviada: false,
    executada: false,
    escrita: false,
    commited: false,
    descartada: false,
  },
  {
    id: "3",
    nome: "Mul",
    entrada1: "F0",
    entrada2: "F2",
    entrada3: "F4",
    enviada: false,
    executada: false,
    escrita: false,
    commited: false,
    descartada: false,
  },
  {
    id: "4",
    nome: "Sub",
    entrada1: "F8",
    entrada2: "F6",
    entrada3: "F2",
    enviada: false,
    executada: false,
    escrita: false,
    commited: false,
    descartada: false,
  },
  {
    id: "5",
    nome: "B",
    entrada1: "F15",
    entrada2: "1",
    entrada3: "R9",
    enviada: false,
    executada: false,
    escrita: false,
    commited: false,
    descartada: false,
  },
  {
    id: "6",
    nome: "Div",
    entrada1: "F10",
    entrada2: "F0",
    entrada3: "F6",
    enviada: false,
    executada: false,
    escrita: false,
    commited: false,
    descartada: false,
  },
  {
    id: "7",
    nome: "Add",
    entrada1: "F6",
    entrada2: "F8",
    entrada3: "F2",
    enviada: false,
    executada: false,
    escrita: false,
    commited: false,
    descartada: false,
  },
];
